Repository Ox-Chema-xO/Plataforma-de-control-de-calidad-de-codigo-, pull requests merged in 2025-06, with the labels that each got.

#10 feat: implementa gestor de directorios en helpers para log y reporting
  requirements.txt
  scripts/setup.sh
  src/helpers/gestor_directorios.py
  tests/test_helpers.py
Labels: sprint1

#11 feat: implementa gestor de archivos en helpers como apoyo para logs y reporting
  src/helpers/gestor_archivos.py
  tests/test_helpers.py
Labels: sprint1

#12 Feature/list functions
  src/utils/list_utils.py
  tests/test_list_utils.py
  tests/test_list_utils_exceptions.py
Labels: sprint1

#13 feat: crea RegistradorLogs y define metodos para el registro de logs (flake8, pytest, shellcheck)
  src/logs/registrador_logs.py
  tests/test_logs.py
Labels: sprint1

#15 feat: crea la clase Reportador e implementa metodos para la generacion de reportes de estado del sistema
  src/reporting/reportador.py
  tests/test_reportador.py
Labels: sprint1

#17 feat: implementar módulo terraform con validación HCL2
  .gitignore
  hooks/pre-commit
  iac/main.tf
  iac_tests/test_terraform_validation.py
  requirements.txt
Labels: sprint1

#27 release: integrar cambios del Sprint 1
  .gitignore
  README.md
  hooks/pre-commit
  iac/main.tf
  iac_tests/test_terraform_validation.py
  requirements.txt
  scripts/lint_qa.sh
  scripts/run_tests.sh
  scripts/setup.sh
  src/helpers/gestor_archivos.py
  src/helpers/gestor_directorios.py
  src/logs/registrador_logs.py
  src/reporting/reportador.py
  src/utils/list_utils.py
  src/utils/string_utils.py
  tests/conftest.py
  tests/test_helpers.py
  tests/test_list_utils.py
  tests/test_list_utils_exceptions.py
  tests/test_logs.py
  tests/test_reportador.py
  tests/test_string_utils.py
  tests/test_string_utils_exceptions.py
Labels: sprint1

#28 feat: añade nuevas fixtures de tipo module y function en conftest.py
  tests/conftest.py
  tests/test_list_utils.py
  tests/test_string_utils.py
Labels: Sprint 2

#29 feat(iac): implementar módulo de variables Terraform
  iac/main.tf
  iac/variables.tf
Labels: Sprint 2

#30 feat: implementa patch.object y pytest.create_autospec en los test de los metodos de utils/
  tests/test_list_utils_exceptions.py
  tests/test_string_utils_con_mock.py
Labels: Sprint 2

#31 feat: Crea tests con monkeypatch para simular llamadas a funciones del sistema (os)
  tests/test_monkeypatch_simulation.py
Labels: Sprint 2

#48 feat: agrega fixtures avanzadas con factories y fixture anidada
  tests/conftest.py
  tests/test_fixture_factory.py
Labels: Sprint 3
